# ai-report-generator/backend/app/pdf/layouts.py
from reportlab.platypus import Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime
from app.pdf.styles import get_styles

class CoverPage:
    """Create cover page elements."""
    
    @staticmethod
    def create(title: str, date: str, author: str = "AI Report Generator"):
        """Create cover page story elements."""
        styles = get_styles()
        story = []
        
        # Add spacing for vertical centering
        story.append(Spacer(1, 2.5 * inch))
        
        # Add title
        story.append(Paragraph(title, styles['CoverTitle']))
        story.append(Spacer(1, 0.5 * inch))
        
        # Add subtitle
        story.append(Paragraph("Technical Report", styles['CoverSubtitle']))
        story.append(Spacer(1, 0.3 * inch))
        
        # Add project type
        story.append(Paragraph("Generated by AI Report Generator", styles['CoverInfo']))
        story.append(Spacer(1, 2 * inch))
        
        # Add date
        story.append(Paragraph(f"Date: {date}", styles['CoverInfo']))
        
        # Add author
        story.append(Paragraph(f"Author: {author}", styles['CoverInfo']))
        
        # Add page break after cover
        story.append(PageBreak())
        
        return story

class TableOfContents:
    """Create table of contents elements."""
    
    @staticmethod
    def create():
        """Create table of contents story elements."""
        styles = get_styles()
        story = []
        
        # Add TOC heading
        story.append(Paragraph("Table of Contents", styles['TOCHeading']))
        story.append(Spacer(1, 0.3 * inch))
        
        # Define sections and their page numbers (placeholders)
        sections = [
            "Abstract",
            "Introduction",
            "Problem Statement",
            "Objectives",
            "Methodology",
            "Tools & Technologies",
            "System Architecture",
            "Implementation",
            "Results & Analysis",
            "Conclusion",
            "Future Scope"
        ]
        
        # Create TOC entries
        for i, section in enumerate(sections, start=1):
            # Create dotted line with page number
            toc_text = f"{section}"
            page_num = i + 2  # Placeholder page numbers
            
            # Create table for TOC entry with dotted leader
            data = [[
                Paragraph(f"{i}. {section}", styles['TableOfContents']),
                Paragraph(". " * 50, styles['TableOfContents']),
                Paragraph(str(page_num), styles['TableOfContents'])
            ]]
            
            table = Table(data, colWidths=[2.5*inch, 3.5*inch, 0.5*inch])
            table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (0, 0), 'LEFT'),
                ('ALIGN', (1, 0), (1, 0), 'CENTER'),
                ('ALIGN', (2, 0), (2, 0), 'RIGHT'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (0, 0), 0),
                ('RIGHTPADDING', (2, 0), (2, 0), 0),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
            ]))
            
            story.append(table)
        
        return story