from typing import List, Optional, Tuple

from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, Spacer, Table, TableStyle

from app.pdf.styles import get_styles


class CoverPage:
    """Render the report cover page."""

    @staticmethod
    def create(title: str, date: str, author: str = "AI Report Generator") -> List:
        styles = get_styles()
        return [
            Spacer(1, 2.5 * inch),
            Paragraph(title, styles["CoverTitle"]),
            Spacer(1, 0.5 * inch),
            Paragraph("Technical Report", styles["CoverSubtitle"]),
            Spacer(1, 0.3 * inch),
            Paragraph("Generated by AI Report Generator", styles["CoverInfo"]),
            Spacer(1, 2 * inch),
            Paragraph(f"Date: {date}", styles["CoverInfo"]),
            Paragraph(f"Author: {author}", styles["CoverInfo"]),
            PageBreak(),
        ]


class TableOfContents:
    """Render a Table of Contents from a list of (label, page) pairs."""

    DEFAULT_ENTRIES: List[Tuple[str, Optional[int]]] = [
        ("Abstract", None),
        ("1. Introduction", None),
        ("2. Project Analysis", None),
        ("3. Software Requirement Specification (SRS)", None),
        ("4. System Design & Architecture", None),
        ("5. Implementation (Development Phase)", None),
        ("6. Testing & Quality Assurance", None),
        ("7. Results & Discussion", None),
        ("8. Challenges & Learnings", None),
        ("9. Conclusion & Future Scope", None),
        ("10. References", None),
        ("11. Appendices", None),
    ]

    @staticmethod
    def create(
        entries: Optional[List[Tuple[str, Optional[int]]]] = None,
    ) -> List:
        styles = get_styles()
        story: List = [
            Paragraph("Table of Contents", styles["TOCHeading"]),
            Spacer(1, 0.3 * inch),
        ]

        rows = entries if entries else TableOfContents.DEFAULT_ENTRIES

        for label, page in rows:
            page_str = str(page) if page is not None else ""
            data = [
                [
                    Paragraph(label, styles["TableOfContents"]),
                    Paragraph(". " * 50, styles["TableOfContents"]),
                    Paragraph(page_str, styles["TableOfContents"]),
                ]
            ]
            table = Table(data, colWidths=[3.7 * inch, 2.3 * inch, 0.5 * inch])
            table.setStyle(
                TableStyle(
                    [
                        ("ALIGN", (0, 0), (0, 0), "LEFT"),
                        ("ALIGN", (1, 0), (1, 0), "CENTER"),
                        ("ALIGN", (2, 0), (2, 0), "RIGHT"),
                        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                        ("LEFTPADDING", (0, 0), (0, 0), 0),
                        ("RIGHTPADDING", (2, 0), (2, 0), 0),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                    ]
                )
            )
            story.append(table)

        story.append(PageBreak())
        return story
